-- MySQL Script generated by MySQL Workbench
-- Mon Sep 19 13:31:21 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema barberapp
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema barberapp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `barberapp` DEFAULT CHARACTER SET utf8mb4 ;
USE `barberapp` ;

-- -----------------------------------------------------
-- Table `barberapp`.`barbershops`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `barberapp`.`barbershops` (
  `id` BIGINT(20) NOT NULL,
  `cellphone` VARCHAR(10) NOT NULL,
  `city` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(200) NOT NULL,
  `location` VARCHAR(255) NULL DEFAULT NULL,
  `nickname` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `photo` VARCHAR(255) NULL DEFAULT NULL,
  `qualification` DOUBLE NULL DEFAULT NULL,
  `type_user` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_sem8wgs1bwvklnrc4hb0bd4sq` (`email` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `barberapp`.`barber`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `barberapp`.`barber` (
  `id` BIGINT(20) NOT NULL,
  `age` DATE NOT NULL,
  `cellphone` VARCHAR(10) NOT NULL,
  `city` VARCHAR(255) NOT NULL,
  `description` VARCHAR(300) NULL DEFAULT NULL,
  `email` VARCHAR(200) NOT NULL,
  `nickname` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `photo` VARCHAR(255) NULL DEFAULT NULL,
  `qualification` DOUBLE NULL DEFAULT NULL,
  `type_user` INT(11) NOT NULL,
  `barbershop_id` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_uvdbxox55254tu9swti0fae5` (`email` ASC),
  INDEX `FKhue66838xlsx4eqvqhj44k03y` (`barbershop_id` ASC),
  CONSTRAINT `FKhue66838xlsx4eqvqhj44k03y`
    FOREIGN KEY (`barbershop_id`)
    REFERENCES `barberapp`.`barbershops` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `barberapp`.`bindings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `barberapp`.`bindings` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `acceptance` BIT(1) NULL DEFAULT NULL,
  `barber` BIGINT(20) NULL DEFAULT NULL,
  `barbershop` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKgnn6nttofriug9kfo002aftd9` (`barber` ASC),
  INDEX `FKjig90g2kfsi5ngs6d9hp7o80x` (`barbershop` ASC),
  CONSTRAINT `FKgnn6nttofriug9kfo002aftd9`
    FOREIGN KEY (`barber`)
    REFERENCES `barberapp`.`barber` (`id`),
  CONSTRAINT `FKjig90g2kfsi5ngs6d9hp7o80x`
    FOREIGN KEY (`barbershop`)
    REFERENCES `barberapp`.`barbershops` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `barberapp`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `barberapp`.`customers` (
  `id` BIGINT(20) NOT NULL,
  `age` DATE NOT NULL,
  `cellphone` VARCHAR(10) NOT NULL,
  `city` VARCHAR(255) NOT NULL,
  `email` VARCHAR(200) NOT NULL,
  `nickname` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `photo` VARCHAR(255) NULL DEFAULT NULL,
  `type_user` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_rfbvkrffamfql7cjmen8v976v` (`email` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `barberapp`.`booking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `barberapp`.`booking` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `barbershop` INT(11) NULL DEFAULT NULL,
  `cancelled` BIT(1) NULL DEFAULT NULL,
  `completed` BIT(1) NULL DEFAULT NULL,
  `reservation_date` DATETIME NULL DEFAULT NULL,
  `barber_id` BIGINT(20) NULL DEFAULT NULL,
  `customer_id` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK1p8d1rwmvewb8qx73gcdbdocq` (`barber_id` ASC),
  INDEX `FKso8gpp93vegy1aal4p2bfst8j` (`customer_id` ASC),
  CONSTRAINT `FK1p8d1rwmvewb8qx73gcdbdocq`
    FOREIGN KEY (`barber_id`)
    REFERENCES `barberapp`.`barber` (`id`),
  CONSTRAINT `FKso8gpp93vegy1aal4p2bfst8j`
    FOREIGN KEY (`customer_id`)
    REFERENCES `barberapp`.`customers` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `barberapp`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `barberapp`.`users` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `cellphone` VARCHAR(10) NULL DEFAULT NULL,
  `city` VARCHAR(60) NULL DEFAULT NULL,
  `date_or_birth` DATE NULL DEFAULT NULL,
  `enabled` BIT(1) NULL DEFAULT NULL,
  `nickname` VARCHAR(200) NULL DEFAULT NULL,
  `password` VARCHAR(60) NULL DEFAULT NULL,
  `type_user` INT(11) NULL DEFAULT NULL,
  `username` VARCHAR(200) NULL DEFAULT NULL,
  `cuts` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_2ty1xmrrgtn89xt7kyxx6ta7h` (`nickname` ASC),
  UNIQUE INDEX `UK_r43af9ap4edm43mmtq01oddj6` (`username` ASC),
  INDEX `FKmrgqb5hefli9dqr2m2fvmeqhr` (`cuts` ASC),
  CONSTRAINT `FKmrgqb5hefli9dqr2m2fvmeqhr`
    FOREIGN KEY (`cuts`)
    REFERENCES `barberapp`.`cuts` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `barberapp`.`cuts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `barberapp`.`cuts` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `url` VARCHAR(255) NULL DEFAULT NULL,
  `id_user` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKmnnj3jl7csfwskgyvhhoq2xsa` (`id_user` ASC),
  CONSTRAINT `FKmnnj3jl7csfwskgyvhhoq2xsa`
    FOREIGN KEY (`id_user`)
    REFERENCES `barberapp`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `barberapp`.`images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `barberapp`.`images` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(100) NULL DEFAULT NULL,
  `name` VARCHAR(30) NULL DEFAULT NULL,
  `url` VARCHAR(200) NULL DEFAULT NULL,
  `barbershop_id` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK1wd9uhkxfosrlsrge4vauf5l` (`barbershop_id` ASC),
  CONSTRAINT `FK1wd9uhkxfosrlsrge4vauf5l`
    FOREIGN KEY (`barbershop_id`)
    REFERENCES `barberapp`.`barbershops` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `barberapp`.`promotions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `barberapp`.`promotions` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(100) NULL DEFAULT NULL,
  `name` VARCHAR(30) NULL DEFAULT NULL,
  `url` VARCHAR(200) NULL DEFAULT NULL,
  `owner` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKf0hqi61xipd7mj2x6i246nxmr` (`owner` ASC),
  CONSTRAINT `FKf0hqi61xipd7mj2x6i246nxmr`
    FOREIGN KEY (`owner`)
    REFERENCES `barberapp`.`barbershops` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `barberapp`.`publication`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `barberapp`.`publication` (
  `id_publication` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `url` VARCHAR(255) NULL DEFAULT NULL,
  `id_barber` BIGINT(20) NULL DEFAULT NULL,
  `id_barbershop` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id_publication`),
  INDEX `FK3qql1oqcx852hyvmawr625eqi` (`id_barber` ASC),
  INDEX `FKde8h3plah2tjdaywipbpcuq5x` (`id_barbershop` ASC),
  CONSTRAINT `FK3qql1oqcx852hyvmawr625eqi`
    FOREIGN KEY (`id_barber`)
    REFERENCES `barberapp`.`barber` (`id`),
  CONSTRAINT `FKde8h3plah2tjdaywipbpcuq5x`
    FOREIGN KEY (`id_barbershop`)
    REFERENCES `barberapp`.`barbershops` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `barberapp`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `barberapp`.`roles` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_ldv0v52e0udsh2h1rs0r0gw1n` (`nombre` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `barberapp`.`users_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `barberapp`.`users_roles` (
  `user_id` BIGINT(20) NOT NULL,
  `role_id` BIGINT(20) NOT NULL,
  UNIQUE INDEX `UKq3r1u8cne2rw2hkr899xuh7vj` (`user_id` ASC, `role_id` ASC),
  INDEX `FKj6m8fwv7oqv74fcehir1a9ffy` (`role_id` ASC),
  CONSTRAINT `FK2o0jvgh89lemvvo17cbqvdxaa`
    FOREIGN KEY (`user_id`)
    REFERENCES `barberapp`.`users` (`id`),
  CONSTRAINT `FKj6m8fwv7oqv74fcehir1a9ffy`
    FOREIGN KEY (`role_id`)
    REFERENCES `barberapp`.`roles` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

USE `barberapp` ;

-- -----------------------------------------------------
-- Placeholder table for view `barberapp`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `barberapp`.`view1` (`id` INT);

-- -----------------------------------------------------
-- View `barberapp`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `barberapp`.`view1`;
USE `barberapp`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
